import org.apache.tools.ant.taskdefs.condition.Os

plugins {
	id("fabric-loom") version "1.10.0-bta"
	id 'maven-publish'
	id 'com.matthewprenger.cursegradle' version '1.+'
	id "com.modrinth.minotaur" version "2.+"
}

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

def lwjglVersion = "3.3.4"

def lwjglNatives
if (Os.isFamily(Os.FAMILY_UNIX) && !Os.isFamily(Os.FAMILY_MAC)) {
	lwjglNatives = "natives-linux"
} else if (Os.isFamily(Os.FAMILY_WINDOWS)) {
	lwjglNatives = "natives-windows"
} else if (Os.isFamily(Os.FAMILY_MAC)) {
	lwjglNatives = "natives-macos" + (Os.isArch("aarch64") ? "-arm64" : "")
} else {
	throw new GradleException("Unsupported OS")
}


loom {
	noIntermediateMappings()
	customMinecraftMetadata.set("https://downloads.betterthanadventure.net/bta-client/$bta_channel/v$bta_version/manifest.json")
}

repositories {
	mavenCentral()
	maven {
		url = uri("https://jitpack.io")
	}
	maven {
		name = "Babric"
		url = uri("https://maven.glass-launcher.net/babric")
	}
	maven {
		name = "Fabric"
		url = uri("https://maven.fabricmc.net/")
	}
	maven {
		name = "SignalumMavenInfrastructure"
		url = uri("https://maven.thesignalumproject.net/infrastructure")
	}
	maven {
		name = "SignalumMavenReleases"
		url = uri("https://maven.thesignalumproject.net/releases")
	}
	ivy {
		url = uri("https://github.com/Better-than-Adventure")
		patternLayout {
			artifact "[organisation]/releases/download/v[revision]/[module].jar"
		}
		metadataSources {
			artifact()
		}
	}
	ivy {
		url = uri("https://downloads.betterthanadventure.net/bta-client/${bta_channel}/")
		patternLayout {
			artifact "/v[revision]/client.jar"
		}
		metadataSources {
			artifact()
		}
	}
	ivy {
		url = uri("https://downloads.betterthanadventure.net/bta-server/${bta_channel}/")
		patternLayout {
			artifact "/v[revision]/server.jar"
		}
		metadataSources {
			artifact()
		}
	}
	ivy {
		url = uri("https://piston-data.mojang.com")
		patternLayout {
			artifact "v1/[organisation]/[revision]/[module].jar"
		}
		metadataSources {
			artifact()
		}
	}
}


dependencies {
	minecraft("::${bta_version}")
	mappings(loom.layered {})

	modRuntimeOnly("objects:client:43db9b498cb67058d2e12d394e6507722e71bb45") // https://piston-data.mojang.com/v1/objects/43db9b498cb67058d2e12d394e6507722e71bb45/client.jar
	modImplementation("net.fabricmc:fabric-loader:$project.loader_version")

	// Helper library
	// If you do not need Halplibe you can comment this line out or delete this line
	modImplementation("turniplabs:halplibe:$project.halplibe_version")

	modImplementation("turniplabs:modmenu-bta:$project.mod_menu_version")

	implementation("org.slf4j:slf4j-api:1.8.0-beta4")
	implementation("org.apache.logging.log4j:log4j-slf4j18-impl:2.16.0")

	implementation("com.google.guava:guava:33.0.0-jre")
	implementation("com.google.code.gson:gson:2.10.1")

	var log4jVersion = "2.20.0"
	implementation("org.apache.logging.log4j:log4j-core:$log4jVersion")
	implementation("org.apache.logging.log4j:log4j-api:$log4jVersion")
	implementation("org.apache.logging.log4j:log4j-1.2-api:$log4jVersion")

	implementation("org.apache.commons:commons-lang3:3.12.0")
	include("org.apache.commons:commons-lang3:3.12.0")

	modImplementation("com.github.Better-than-Adventure:legacy-lwjgl3:1.0.5")
	implementation(platform("org.lwjgl:lwjgl-bom:$lwjglVersion"))

	runtimeOnly("org.lwjgl:lwjgl::$lwjglNatives")
	runtimeOnly("org.lwjgl:lwjgl-assimp::$lwjglNatives")
	runtimeOnly("org.lwjgl:lwjgl-glfw::$lwjglNatives")
	runtimeOnly("org.lwjgl:lwjgl-openal::$lwjglNatives")
	runtimeOnly("org.lwjgl:lwjgl-opengl::$lwjglNatives")
	runtimeOnly("org.lwjgl:lwjgl-stb::$lwjglNatives")
	implementation("org.lwjgl:lwjgl:$lwjglVersion")
	implementation("org.lwjgl:lwjgl-assimp:$lwjglVersion")
	implementation("org.lwjgl:lwjgl-glfw:$lwjglVersion")
	implementation("org.lwjgl:lwjgl-openal:$lwjglVersion")
	implementation("org.lwjgl:lwjgl-opengl:$lwjglVersion")
	implementation("org.lwjgl:lwjgl-stb:$lwjglVersion")
}

if (System.getenv("CURSEFORGE_TOKEN") != null) {
	curseforge {
		apiKey = System.getenv("CURSEFORGE_TOKEN")
		project {
			id = '517673'
			changelog = project.changelog
			releaseType = 'release'
			addGameVersion "Fabric"
			addGameVersion "b1.7.3"
			relations {
				//requiredDependency "legacy-fabric-api"
				//optionalDependency "simple-backpack-fabric"
			}

			mainArtifact(tasks.remapJar)
		}
	}
}

if (System.getenv("MODRINTH_TOKEN") != null) {
	modrinth {
		token = System.getenv("MODRINTH_TOKEN")
		projectId = 'styMEyoE'
		versionNumber = project.mod_version + "-bta"
		gameVersions = ["b1.7.3"]
		versionType = 'release'
		uploadFile = tasks.remapJar
		changelog = project.changelog
		loaders = ["bta"]
		dependencies {
			//required.project "legacy-fabric-api" // Fabric API
		}
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	// If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"

	// The Minecraft launcher currently installs Java 8 for users, so your mod probably wants to target Java 8 too
	// JDK 9 introduced a new way of specifying this that will make sure no newer classes or methods are used.
	// We'll use that if it's available, but otherwise we'll use the older option.
	def targetVersion = 8
	if (JavaVersion.current().isJava9Compatible()) {
		 it.options.release = targetVersion
	}
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			// add all the jars that should be included when publishing to maven
			artifact(remapJar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
