# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

minecraft_version=1.12.2
yarn_mappings=1.12.2+build.571
loader_version=0.16.14

# Legacy Fabric API
fabric_version=1.12.0+1.12.2
# Mod Properties
mod_version = 1.4.0-1.14.4
maven_group = net.pitan76
archives_base_name = storagebox

changelog = backport to 1.12.2