# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

minecraft_version=1.20.5
yarn_mappings=1.20.5+build.1
loader_version=0.18.4

# Fabric API
fabric_version=0.97.8+1.20.5

# Mod Properties
mod_version = 1.4.8-1.20.5
maven_group = net.pitan76
archives_base_name = storagebox

changelog = Fixed a bug where changes to a component of the same item were not reflected (exam.bundle) \
  Fixed a bug where the StorageBox count overflowed when exceeding 214743647 \
  Added the tag "storagebox:storagebox_blacklist" to control items that cannot be placed in the StorageBox (default is none) \
  Fixed a bug that empty bucket is not returned when using bucket with fluid in StorageBox. \
  Fixed a bug that allowed items to be stored in slots where they normally couldn't be stored.(Fuel slot for the stove, result slot, etc.) \
  Fixed a bug that allowed infinite recovery from the result slot of Crafter/Crafting Table. \
  Fixed a bug that allowed recovery from slots that should not be recoverable or invalid slots. (by Minor2CCh)