# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# BTA
bta_version=7.3_04
bta_channel=release

# Loader
loader_version=0.15.6-bta.7

# Other Mods
mod_menu_version=3.0.0
halplibe_version=5.2.4

# Mod Properties
mod_version = 1.4.0-b1.7.3
maven_group = net.pitan76
archives_base_name = storagebox

changelog = backport to b1.7.3